import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { signIn, signOut, useSession } from 'next-auth/client';

export default function Home() {
  const [sub, setSub] = useState('');

  const [session, loading] = useSession();

  return (
    <div
      className='flex flex-col items-center justify-center min-h-screen bg-black'
      style={{
        backgroundImage:
          'linear-gradient(rgb(0 0 0 / 60%), rgb(0 0 0 / 60%)), url(/images/hero-banner.jpeg)',
      }}
    >
      <Head>
        <title>Felix - Netflix Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col items-center justify-center flex-1  text-center text-white max-w-lg '>
        {!session && (
          <>
            Not signed in <br />
            <button>Sign in</button>
          </>
        )}
        {session && (
          <>
            Signed in as {session.user.email} <br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}

        <h1 className='text-5xl font-bold my-4'>
          Unlimited movies, TV shows, and more
        </h1>
        <div className='text-2xl mt-4 mb-8'>Watch anywhere. Cancel anytime</div>
        <p>
          Ready to watch? Enter your email to create or restart your membership
        </p>

        <div className='flex mt-5'>
          <input
            type='email'
            placeholder='Email address'
            className=' bg-white p-4 min-w-[400px] text-gray-500'
            name='subcriber'
            onChange={(e) => setSub(e.target.value)}
            value={sub}
          />
          <button
            className='flex items-center bg-[#F41612] text-white text-lg px-8 capitalize whitespace-nowrap'
            onClick={() => signIn('google')}
          >
            get started
            <svg
              xmlns='http://www.w3.org/2000/svg'
              className='w-5'
              fill='none'
              viewBox='0 0 24 24'
              stroke='currentColor'
            >
              <path
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth={2}
                d='M9 5l7 7-7 7'
              />
            </svg>
          </button>
        </div>
      </main>
    </div>
  );
}
